// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemeCaisse.Infrastructure.Data;

#nullable disable

namespace SystemeCaisse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314115036_AddAdvancedPromotions")]
    partial class AddAdvancedPromotions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SystemeCaisse.Core.Entities.CommandeFournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLivraisonPrevue")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("CommandesFournisseurs");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HorairesDimanche")
                        .HasColumnType("TEXT");

                    b.Property<string>("HorairesSemaine")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Siret")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Mon Magasin",
                            UpdatedAt = new DateTime(2026, 3, 14, 12, 50, 30, 573, DateTimeKind.Local).AddTicks(7311)
                        });
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.HistoriqueAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonneesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Utilisateur")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoriqueActions");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Inventaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventaires");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.LigneInventaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteReelle")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantiteSysteme")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("ValeurEcart")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventaireId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesInventaire");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.LigneVente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategorieNom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProduitNom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionAppliquee")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("Remise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLigne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("VenteId");

                    b.ToTable("LignesVente");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProduitNomSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.PlanningPromotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaires")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbVentes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromotionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("PlanningPromotions");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeBarre")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockActuel")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockAlerte")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeVente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Cumulable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IemeArticle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPourcentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("QuantiteOfferte")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RemiseSurIeme")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SeuilPanier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SeuilQuantite")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypePromotion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valeur")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.PromotionTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PromotionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantiteMin")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionTiers");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.SystemConfiguration", b =>
                {
                    b.Property<string>("Cle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .HasColumnType("TEXT");

                    b.HasKey("Cle");

                    b.ToTable("Configuration");

                    b.HasData(
                        new
                        {
                            Cle = "version",
                            Description = "Version de l'application",
                            Type = "text",
                            Valeur = "1.0.0"
                        },
                        new
                        {
                            Cle = "theme",
                            Type = "text",
                            Valeur = "default"
                        });
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonnaieRendue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantCB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantEspeces")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoyenPaiement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("NbArticles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRemise")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.CommandeFournisseur", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.LigneInventaire", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Inventaire", "Inventaire")
                        .WithMany("Lignes")
                        .HasForeignKey("InventaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemeCaisse.Core.Entities.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventaire");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.LigneVente", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId");

                    b.HasOne("SystemeCaisse.Core.Entities.Vente", "Vente")
                        .WithMany("Lignes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.MouvementStock", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.PlanningPromotion", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Produit", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Promotion", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.PromotionTier", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Promotion", "Promotion")
                        .WithMany("Tiers")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Inventaire", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Promotion", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Vente", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
