// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemeCaisse.Infrastructure.Data;

#nullable disable

namespace SystemeCaisse.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221152808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HorairesDimanche")
                        .HasColumnType("TEXT");

                    b.Property<string>("HorairesSemaine")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Siret")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Mon Magasin",
                            UpdatedAt = new DateTime(2025, 12, 21, 16, 28, 6, 968, DateTimeKind.Local).AddTicks(5194)
                        });
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.LigneVente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProduitNom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("TotalLigne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("VenteId");

                    b.ToTable("LignesVente");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeBarre")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActuel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockAlerte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeVente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.SystemConfiguration", b =>
                {
                    b.Property<string>("Cle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .HasColumnType("TEXT");

                    b.HasKey("Cle");

                    b.ToTable("Configuration");

                    b.HasData(
                        new
                        {
                            Cle = "version",
                            Description = "Version de l'application",
                            Type = "text",
                            Valeur = "1.0.0"
                        },
                        new
                        {
                            Cle = "theme",
                            Type = "text",
                            Valeur = "default"
                        });
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoyenPaiement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("NbArticles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.LigneVente", b =>
                {
                    b.HasOne("SystemeCaisse.Core.Entities.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId");

                    b.HasOne("SystemeCaisse.Core.Entities.Vente", "Vente")
                        .WithMany("Lignes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("SystemeCaisse.Core.Entities.Vente", b =>
                {
                    b.Navigation("Lignes");
                });
#pragma warning restore 612, 618
        }
    }
}
